// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _duckdb_copy_function_finalize_info {
 *     void *internal_ptr;
 * }
 * }
 */
public class _duckdb_copy_function_finalize_info {

    _duckdb_copy_function_finalize_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_h.C_POINTER.withName("internal_ptr")
    ).withName("_duckdb_copy_function_finalize_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout internal_ptr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("internal_ptr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *internal_ptr
     * }
     */
    public static final AddressLayout internal_ptr$layout() {
        return internal_ptr$LAYOUT;
    }

    private static final long internal_ptr$OFFSET = $LAYOUT.byteOffset(groupElement("internal_ptr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *internal_ptr
     * }
     */
    public static final long internal_ptr$offset() {
        return internal_ptr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *internal_ptr
     * }
     */
    public static MemorySegment internal_ptr(MemorySegment struct) {
        return struct.get(internal_ptr$LAYOUT, internal_ptr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *internal_ptr
     * }
     */
    public static void internal_ptr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(internal_ptr$LAYOUT, internal_ptr$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

