// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct duckdb_extension_access {
 *     void (*set_error)(duckdb_extension_info, const char *);
 *     duckdb_database *(*get_database)(duckdb_extension_info);
 *     const void *(*get_api)(duckdb_extension_info, const char *);
 * }
 * }
 */
public class duckdb_extension_access {

    duckdb_extension_access() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_h.C_POINTER.withName("set_error"),
        duckdb_h.C_POINTER.withName("get_database"),
        duckdb_h.C_POINTER.withName("get_api")
    ).withName("duckdb_extension_access");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*set_error)(duckdb_extension_info, const char *)
     * }
     */
    public final static class set_error {

        private set_error() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            duckdb_h.C_POINTER,
            duckdb_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = duckdb_h.upcallHandle(set_error.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_error.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_error$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_error)(duckdb_extension_info, const char *)
     * }
     */
    public static final AddressLayout set_error$layout() {
        return set_error$LAYOUT;
    }

    private static final long set_error$OFFSET = $LAYOUT.byteOffset(groupElement("set_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_error)(duckdb_extension_info, const char *)
     * }
     */
    public static final long set_error$offset() {
        return set_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_error)(duckdb_extension_info, const char *)
     * }
     */
    public static MemorySegment set_error(MemorySegment struct) {
        return struct.get(set_error$LAYOUT, set_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_error)(duckdb_extension_info, const char *)
     * }
     */
    public static void set_error(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_error$LAYOUT, set_error$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * duckdb_database *(*get_database)(duckdb_extension_info)
     * }
     */
    public final static class get_database {

        private get_database() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            duckdb_h.C_POINTER,
            duckdb_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = duckdb_h.upcallHandle(get_database.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_database.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_database$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_database"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * duckdb_database *(*get_database)(duckdb_extension_info)
     * }
     */
    public static final AddressLayout get_database$layout() {
        return get_database$LAYOUT;
    }

    private static final long get_database$OFFSET = $LAYOUT.byteOffset(groupElement("get_database"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * duckdb_database *(*get_database)(duckdb_extension_info)
     * }
     */
    public static final long get_database$offset() {
        return get_database$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * duckdb_database *(*get_database)(duckdb_extension_info)
     * }
     */
    public static MemorySegment get_database(MemorySegment struct) {
        return struct.get(get_database$LAYOUT, get_database$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * duckdb_database *(*get_database)(duckdb_extension_info)
     * }
     */
    public static void get_database(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_database$LAYOUT, get_database$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * const void *(*get_api)(duckdb_extension_info, const char *)
     * }
     */
    public final static class get_api {

        private get_api() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            duckdb_h.C_POINTER,
            duckdb_h.C_POINTER,
            duckdb_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = duckdb_h.upcallHandle(get_api.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_api.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_api$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_api"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *(*get_api)(duckdb_extension_info, const char *)
     * }
     */
    public static final AddressLayout get_api$layout() {
        return get_api$LAYOUT;
    }

    private static final long get_api$OFFSET = $LAYOUT.byteOffset(groupElement("get_api"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *(*get_api)(duckdb_extension_info, const char *)
     * }
     */
    public static final long get_api$offset() {
        return get_api$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *(*get_api)(duckdb_extension_info, const char *)
     * }
     */
    public static MemorySegment get_api(MemorySegment struct) {
        return struct.get(get_api$LAYOUT, get_api$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *(*get_api)(duckdb_extension_info, const char *)
     * }
     */
    public static void get_api(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_api$LAYOUT, get_api$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

