// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     void *deprecated_data;
 *     bool *deprecated_nullmask;
 *     duckdb_type deprecated_type;
 *     char *deprecated_name;
 *     void *internal_data;
 * }
 * }
 */
public class duckdb_column {

    duckdb_column() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_h.C_POINTER.withName("deprecated_data"),
        duckdb_h.C_POINTER.withName("deprecated_nullmask"),
        duckdb_h.C_INT.withName("deprecated_type"),
        MemoryLayout.paddingLayout(4),
        duckdb_h.C_POINTER.withName("deprecated_name"),
        duckdb_h.C_POINTER.withName("internal_data")
    ).withName("$anon$451:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout deprecated_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("deprecated_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *deprecated_data
     * }
     */
    public static final AddressLayout deprecated_data$layout() {
        return deprecated_data$LAYOUT;
    }

    private static final long deprecated_data$OFFSET = $LAYOUT.byteOffset(groupElement("deprecated_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *deprecated_data
     * }
     */
    public static final long deprecated_data$offset() {
        return deprecated_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *deprecated_data
     * }
     */
    public static MemorySegment deprecated_data(MemorySegment struct) {
        return struct.get(deprecated_data$LAYOUT, deprecated_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *deprecated_data
     * }
     */
    public static void deprecated_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(deprecated_data$LAYOUT, deprecated_data$OFFSET, fieldValue);
    }

    private static final AddressLayout deprecated_nullmask$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("deprecated_nullmask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool *deprecated_nullmask
     * }
     */
    public static final AddressLayout deprecated_nullmask$layout() {
        return deprecated_nullmask$LAYOUT;
    }

    private static final long deprecated_nullmask$OFFSET = $LAYOUT.byteOffset(groupElement("deprecated_nullmask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool *deprecated_nullmask
     * }
     */
    public static final long deprecated_nullmask$offset() {
        return deprecated_nullmask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool *deprecated_nullmask
     * }
     */
    public static MemorySegment deprecated_nullmask(MemorySegment struct) {
        return struct.get(deprecated_nullmask$LAYOUT, deprecated_nullmask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool *deprecated_nullmask
     * }
     */
    public static void deprecated_nullmask(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(deprecated_nullmask$LAYOUT, deprecated_nullmask$OFFSET, fieldValue);
    }

    private static final OfInt deprecated_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("deprecated_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * duckdb_type deprecated_type
     * }
     */
    public static final OfInt deprecated_type$layout() {
        return deprecated_type$LAYOUT;
    }

    private static final long deprecated_type$OFFSET = $LAYOUT.byteOffset(groupElement("deprecated_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * duckdb_type deprecated_type
     * }
     */
    public static final long deprecated_type$offset() {
        return deprecated_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * duckdb_type deprecated_type
     * }
     */
    public static int deprecated_type(MemorySegment struct) {
        return struct.get(deprecated_type$LAYOUT, deprecated_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * duckdb_type deprecated_type
     * }
     */
    public static void deprecated_type(MemorySegment struct, int fieldValue) {
        struct.set(deprecated_type$LAYOUT, deprecated_type$OFFSET, fieldValue);
    }

    private static final AddressLayout deprecated_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("deprecated_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *deprecated_name
     * }
     */
    public static final AddressLayout deprecated_name$layout() {
        return deprecated_name$LAYOUT;
    }

    private static final long deprecated_name$OFFSET = $LAYOUT.byteOffset(groupElement("deprecated_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *deprecated_name
     * }
     */
    public static final long deprecated_name$offset() {
        return deprecated_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *deprecated_name
     * }
     */
    public static MemorySegment deprecated_name(MemorySegment struct) {
        return struct.get(deprecated_name$LAYOUT, deprecated_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *deprecated_name
     * }
     */
    public static void deprecated_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(deprecated_name$LAYOUT, deprecated_name$OFFSET, fieldValue);
    }

    private static final AddressLayout internal_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("internal_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *internal_data
     * }
     */
    public static final AddressLayout internal_data$layout() {
        return internal_data$LAYOUT;
    }

    private static final long internal_data$OFFSET = $LAYOUT.byteOffset(groupElement("internal_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *internal_data
     * }
     */
    public static final long internal_data$offset() {
        return internal_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *internal_data
     * }
     */
    public static MemorySegment internal_data(MemorySegment struct) {
        return struct.get(internal_data$LAYOUT, internal_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *internal_data
     * }
     */
    public static void internal_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(internal_data$LAYOUT, internal_data$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

