// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int8_t hour;
 *     int8_t min;
 *     int8_t sec;
 *     int32_t micros;
 * }
 * }
 */
public class duckdb_time_struct {

    duckdb_time_struct() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_h.C_CHAR.withName("hour"),
        duckdb_h.C_CHAR.withName("min"),
        duckdb_h.C_CHAR.withName("sec"),
        MemoryLayout.paddingLayout(1),
        duckdb_h.C_INT.withName("micros")
    ).withName("$anon$334:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte hour$LAYOUT = (OfByte)$LAYOUT.select(groupElement("hour"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t hour
     * }
     */
    public static final OfByte hour$layout() {
        return hour$LAYOUT;
    }

    private static final long hour$OFFSET = $LAYOUT.byteOffset(groupElement("hour"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t hour
     * }
     */
    public static final long hour$offset() {
        return hour$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t hour
     * }
     */
    public static byte hour(MemorySegment struct) {
        return struct.get(hour$LAYOUT, hour$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t hour
     * }
     */
    public static void hour(MemorySegment struct, byte fieldValue) {
        struct.set(hour$LAYOUT, hour$OFFSET, fieldValue);
    }

    private static final OfByte min$LAYOUT = (OfByte)$LAYOUT.select(groupElement("min"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t min
     * }
     */
    public static final OfByte min$layout() {
        return min$LAYOUT;
    }

    private static final long min$OFFSET = $LAYOUT.byteOffset(groupElement("min"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t min
     * }
     */
    public static final long min$offset() {
        return min$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t min
     * }
     */
    public static byte min(MemorySegment struct) {
        return struct.get(min$LAYOUT, min$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t min
     * }
     */
    public static void min(MemorySegment struct, byte fieldValue) {
        struct.set(min$LAYOUT, min$OFFSET, fieldValue);
    }

    private static final OfByte sec$LAYOUT = (OfByte)$LAYOUT.select(groupElement("sec"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t sec
     * }
     */
    public static final OfByte sec$layout() {
        return sec$LAYOUT;
    }

    private static final long sec$OFFSET = $LAYOUT.byteOffset(groupElement("sec"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t sec
     * }
     */
    public static final long sec$offset() {
        return sec$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t sec
     * }
     */
    public static byte sec(MemorySegment struct) {
        return struct.get(sec$LAYOUT, sec$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t sec
     * }
     */
    public static void sec(MemorySegment struct, byte fieldValue) {
        struct.set(sec$LAYOUT, sec$OFFSET, fieldValue);
    }

    private static final OfInt micros$LAYOUT = (OfInt)$LAYOUT.select(groupElement("micros"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t micros
     * }
     */
    public static final OfInt micros$layout() {
        return micros$LAYOUT;
    }

    private static final long micros$OFFSET = $LAYOUT.byteOffset(groupElement("micros"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t micros
     * }
     */
    public static final long micros$offset() {
        return micros$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t micros
     * }
     */
    public static int micros(MemorySegment struct) {
        return struct.get(micros$LAYOUT, micros$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t micros
     * }
     */
    public static void micros(MemorySegment struct, int fieldValue) {
        struct.set(micros$LAYOUT, micros$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

