// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     double percentage;
 *     uint64_t rows_processed;
 *     uint64_t total_rows_to_process;
 * }
 * }
 */
public class duckdb_query_progress_type {

    duckdb_query_progress_type() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_h.C_DOUBLE.withName("percentage"),
        duckdb_h.C_LONG.withName("rows_processed"),
        duckdb_h.C_LONG.withName("total_rows_to_process")
    ).withName("$anon$415:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble percentage$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("percentage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double percentage
     * }
     */
    public static final OfDouble percentage$layout() {
        return percentage$LAYOUT;
    }

    private static final long percentage$OFFSET = $LAYOUT.byteOffset(groupElement("percentage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double percentage
     * }
     */
    public static final long percentage$offset() {
        return percentage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double percentage
     * }
     */
    public static double percentage(MemorySegment struct) {
        return struct.get(percentage$LAYOUT, percentage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double percentage
     * }
     */
    public static void percentage(MemorySegment struct, double fieldValue) {
        struct.set(percentage$LAYOUT, percentage$OFFSET, fieldValue);
    }

    private static final OfLong rows_processed$LAYOUT = (OfLong)$LAYOUT.select(groupElement("rows_processed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t rows_processed
     * }
     */
    public static final OfLong rows_processed$layout() {
        return rows_processed$LAYOUT;
    }

    private static final long rows_processed$OFFSET = $LAYOUT.byteOffset(groupElement("rows_processed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t rows_processed
     * }
     */
    public static final long rows_processed$offset() {
        return rows_processed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t rows_processed
     * }
     */
    public static long rows_processed(MemorySegment struct) {
        return struct.get(rows_processed$LAYOUT, rows_processed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t rows_processed
     * }
     */
    public static void rows_processed(MemorySegment struct, long fieldValue) {
        struct.set(rows_processed$LAYOUT, rows_processed$OFFSET, fieldValue);
    }

    private static final OfLong total_rows_to_process$LAYOUT = (OfLong)$LAYOUT.select(groupElement("total_rows_to_process"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t total_rows_to_process
     * }
     */
    public static final OfLong total_rows_to_process$layout() {
        return total_rows_to_process$LAYOUT;
    }

    private static final long total_rows_to_process$OFFSET = $LAYOUT.byteOffset(groupElement("total_rows_to_process"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t total_rows_to_process
     * }
     */
    public static final long total_rows_to_process$offset() {
        return total_rows_to_process$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t total_rows_to_process
     * }
     */
    public static long total_rows_to_process(MemorySegment struct) {
        return struct.get(total_rows_to_process$LAYOUT, total_rows_to_process$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t total_rows_to_process
     * }
     */
    public static void total_rows_to_process(MemorySegment struct, long fieldValue) {
        struct.set(total_rows_to_process$LAYOUT, total_rows_to_process$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

