// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint64_t lower;
 *     uint64_t upper;
 * }
 * }
 */
public class duckdb_uhugeint {

    duckdb_uhugeint() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_h.C_LONG.withName("lower"),
        duckdb_h.C_LONG.withName("upper")
    ).withName("$anon$401:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong lower$LAYOUT = (OfLong)$LAYOUT.select(groupElement("lower"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t lower
     * }
     */
    public static final OfLong lower$layout() {
        return lower$LAYOUT;
    }

    private static final long lower$OFFSET = $LAYOUT.byteOffset(groupElement("lower"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t lower
     * }
     */
    public static final long lower$offset() {
        return lower$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t lower
     * }
     */
    public static long lower(MemorySegment struct) {
        return struct.get(lower$LAYOUT, lower$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t lower
     * }
     */
    public static void lower(MemorySegment struct, long fieldValue) {
        struct.set(lower$LAYOUT, lower$OFFSET, fieldValue);
    }

    private static final OfLong upper$LAYOUT = (OfLong)$LAYOUT.select(groupElement("upper"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t upper
     * }
     */
    public static final OfLong upper$layout() {
        return upper$LAYOUT;
    }

    private static final long upper$OFFSET = $LAYOUT.byteOffset(groupElement("upper"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t upper
     * }
     */
    public static final long upper$offset() {
        return upper$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t upper
     * }
     */
    public static long upper(MemorySegment struct) {
        return struct.get(upper$LAYOUT, upper$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t upper
     * }
     */
    public static void upper(MemorySegment struct, long fieldValue) {
        struct.set(upper$LAYOUT, upper$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

