// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     union {
 *         struct {
 *             uint32_t length;
 *             char prefix[4];
 *             char *ptr;
 *         } pointer;
 *         struct {
 *             uint32_t length;
 *             char inlined[12];
 *         } inlined;
 *     } value;
 * }
 * }
 */
public class duckdb_string_t {

    duckdb_string_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_string_t.value.layout().withName("value")
    ).withName("$anon$425:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * union {
     *     struct {
     *         uint32_t length;
     *         char prefix[4];
     *         char *ptr;
     *     } pointer;
     *     struct {
     *         uint32_t length;
     *         char inlined[12];
     *     } inlined;
     * }
     * }
     */
    public static class value {

        value() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            duckdb_string_t.value.pointer.layout().withName("pointer"),
            duckdb_string_t.value.inlined.layout().withName("inlined")
        ).withName("$anon$426:2");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char prefix[4];
         *     char *ptr;
         * }
         * }
         */
        public static class pointer {

            pointer() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                duckdb_h.C_INT.withName("length"),
                MemoryLayout.sequenceLayout(4, duckdb_h.C_CHAR).withName("prefix"),
                duckdb_h.C_POINTER.withName("ptr")
            ).withName("$anon$427:3");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final OfInt length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("length"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * uint32_t length
             * }
             */
            public static final OfInt length$layout() {
                return length$LAYOUT;
            }

            private static final long length$OFFSET = $LAYOUT.byteOffset(groupElement("length"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * uint32_t length
             * }
             */
            public static final long length$offset() {
                return length$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * uint32_t length
             * }
             */
            public static int length(MemorySegment struct) {
                return struct.get(length$LAYOUT, length$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * uint32_t length
             * }
             */
            public static void length(MemorySegment struct, int fieldValue) {
                struct.set(length$LAYOUT, length$OFFSET, fieldValue);
            }

            private static final SequenceLayout prefix$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("prefix"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * char prefix[4]
             * }
             */
            public static final SequenceLayout prefix$layout() {
                return prefix$LAYOUT;
            }

            private static final long prefix$OFFSET = $LAYOUT.byteOffset(groupElement("prefix"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * char prefix[4]
             * }
             */
            public static final long prefix$offset() {
                return prefix$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * char prefix[4]
             * }
             */
            public static MemorySegment prefix(MemorySegment struct) {
                return struct.asSlice(prefix$OFFSET, prefix$LAYOUT.byteSize());
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * char prefix[4]
             * }
             */
            public static void prefix(MemorySegment struct, MemorySegment fieldValue) {
                MemorySegment.copy(fieldValue, 0L, struct, prefix$OFFSET, prefix$LAYOUT.byteSize());
            }

            private static long[] prefix$DIMS = { 4 };

            /**
             * Dimensions for array field:
             * {@snippet lang=c :
             * char prefix[4]
             * }
             */
            public static long[] prefix$dimensions() {
                return prefix$DIMS;
            }
            private static final VarHandle prefix$ELEM_HANDLE = prefix$LAYOUT.varHandle(sequenceElement());

            /**
             * Indexed getter for field:
             * {@snippet lang=c :
             * char prefix[4]
             * }
             */
            public static byte prefix(MemorySegment struct, long index0) {
                return (byte)prefix$ELEM_HANDLE.get(struct, prefix$OFFSET, index0);
            }

            /**
             * Indexed setter for field:
             * {@snippet lang=c :
             * char prefix[4]
             * }
             */
            public static void prefix(MemorySegment struct, long index0, byte fieldValue) {
                prefix$ELEM_HANDLE.set(struct, prefix$OFFSET, index0, fieldValue);
            }

            private static final AddressLayout ptr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ptr"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * char *ptr
             * }
             */
            public static final AddressLayout ptr$layout() {
                return ptr$LAYOUT;
            }

            private static final long ptr$OFFSET = $LAYOUT.byteOffset(groupElement("ptr"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * char *ptr
             * }
             */
            public static final long ptr$offset() {
                return ptr$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * char *ptr
             * }
             */
            public static MemorySegment ptr(MemorySegment struct) {
                return struct.get(ptr$LAYOUT, ptr$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * char *ptr
             * }
             */
            public static void ptr(MemorySegment struct, MemorySegment fieldValue) {
                struct.set(ptr$LAYOUT, ptr$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout pointer$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("pointer"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char prefix[4];
         *     char *ptr;
         * } pointer
         * }
         */
        public static final GroupLayout pointer$layout() {
            return pointer$LAYOUT;
        }

        private static final long pointer$OFFSET = $LAYOUT.byteOffset(groupElement("pointer"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char prefix[4];
         *     char *ptr;
         * } pointer
         * }
         */
        public static final long pointer$offset() {
            return pointer$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char prefix[4];
         *     char *ptr;
         * } pointer
         * }
         */
        public static MemorySegment pointer(MemorySegment union) {
            return union.asSlice(pointer$OFFSET, pointer$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char prefix[4];
         *     char *ptr;
         * } pointer
         * }
         */
        public static void pointer(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, pointer$OFFSET, pointer$LAYOUT.byteSize());
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char inlined[12];
         * }
         * }
         */
        public static class inlined {

            inlined() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                duckdb_h.C_INT.withName("length"),
                MemoryLayout.sequenceLayout(12, duckdb_h.C_CHAR).withName("inlined")
            ).withName("$anon$432:3");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final OfInt length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("length"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * uint32_t length
             * }
             */
            public static final OfInt length$layout() {
                return length$LAYOUT;
            }

            private static final long length$OFFSET = $LAYOUT.byteOffset(groupElement("length"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * uint32_t length
             * }
             */
            public static final long length$offset() {
                return length$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * uint32_t length
             * }
             */
            public static int length(MemorySegment struct) {
                return struct.get(length$LAYOUT, length$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * uint32_t length
             * }
             */
            public static void length(MemorySegment struct, int fieldValue) {
                struct.set(length$LAYOUT, length$OFFSET, fieldValue);
            }

            private static final SequenceLayout inlined$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("inlined"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * char inlined[12]
             * }
             */
            public static final SequenceLayout inlined$layout() {
                return inlined$LAYOUT;
            }

            private static final long inlined$OFFSET = $LAYOUT.byteOffset(groupElement("inlined"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * char inlined[12]
             * }
             */
            public static final long inlined$offset() {
                return inlined$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * char inlined[12]
             * }
             */
            public static MemorySegment inlined(MemorySegment struct) {
                return struct.asSlice(inlined$OFFSET, inlined$LAYOUT.byteSize());
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * char inlined[12]
             * }
             */
            public static void inlined(MemorySegment struct, MemorySegment fieldValue) {
                MemorySegment.copy(fieldValue, 0L, struct, inlined$OFFSET, inlined$LAYOUT.byteSize());
            }

            private static long[] inlined$DIMS = { 12 };

            /**
             * Dimensions for array field:
             * {@snippet lang=c :
             * char inlined[12]
             * }
             */
            public static long[] inlined$dimensions() {
                return inlined$DIMS;
            }
            private static final VarHandle inlined$ELEM_HANDLE = inlined$LAYOUT.varHandle(sequenceElement());

            /**
             * Indexed getter for field:
             * {@snippet lang=c :
             * char inlined[12]
             * }
             */
            public static byte inlined(MemorySegment struct, long index0) {
                return (byte)inlined$ELEM_HANDLE.get(struct, inlined$OFFSET, index0);
            }

            /**
             * Indexed setter for field:
             * {@snippet lang=c :
             * char inlined[12]
             * }
             */
            public static void inlined(MemorySegment struct, long index0, byte fieldValue) {
                inlined$ELEM_HANDLE.set(struct, inlined$OFFSET, index0, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout inlined$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("inlined"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char inlined[12];
         * } inlined
         * }
         */
        public static final GroupLayout inlined$layout() {
            return inlined$LAYOUT;
        }

        private static final long inlined$OFFSET = $LAYOUT.byteOffset(groupElement("inlined"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char inlined[12];
         * } inlined
         * }
         */
        public static final long inlined$offset() {
            return inlined$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char inlined[12];
         * } inlined
         * }
         */
        public static MemorySegment inlined(MemorySegment union) {
            return union.asSlice(inlined$OFFSET, inlined$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     uint32_t length;
         *     char inlined[12];
         * } inlined
         * }
         */
        public static void inlined(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, inlined$OFFSET, inlined$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         uint32_t length;
     *         char prefix[4];
     *         char *ptr;
     *     } pointer;
     *     struct {
     *         uint32_t length;
     *         char inlined[12];
     *     } inlined;
     * } value
     * }
     */
    public static final GroupLayout value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         uint32_t length;
     *         char prefix[4];
     *         char *ptr;
     *     } pointer;
     *     struct {
     *         uint32_t length;
     *         char inlined[12];
     *     } inlined;
     * } value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         uint32_t length;
     *         char prefix[4];
     *         char *ptr;
     *     } pointer;
     *     struct {
     *         uint32_t length;
     *         char inlined[12];
     *     } inlined;
     * } value
     * }
     */
    public static MemorySegment value(MemorySegment struct) {
        return struct.asSlice(value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         uint32_t length;
     *         char prefix[4];
     *         char *ptr;
     *     } pointer;
     *     struct {
     *         uint32_t length;
     *         char inlined[12];
     *     } inlined;
     * } value
     * }
     */
    public static void value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

