// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     duckdb_date_struct date;
 *     duckdb_time_struct time;
 * }
 * }
 */
public class duckdb_timestamp_struct {

    duckdb_timestamp_struct() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_date_struct.layout().withName("date"),
        duckdb_time_struct.layout().withName("time")
    ).withName("$anon$363:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout date$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("date"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * duckdb_date_struct date
     * }
     */
    public static final GroupLayout date$layout() {
        return date$LAYOUT;
    }

    private static final long date$OFFSET = $LAYOUT.byteOffset(groupElement("date"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * duckdb_date_struct date
     * }
     */
    public static final long date$offset() {
        return date$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * duckdb_date_struct date
     * }
     */
    public static MemorySegment date(MemorySegment struct) {
        return struct.asSlice(date$OFFSET, date$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * duckdb_date_struct date
     * }
     */
    public static void date(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, date$OFFSET, date$LAYOUT.byteSize());
    }

    private static final GroupLayout time$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("time"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * duckdb_time_struct time
     * }
     */
    public static final GroupLayout time$layout() {
        return time$LAYOUT;
    }

    private static final long time$OFFSET = $LAYOUT.byteOffset(groupElement("time"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * duckdb_time_struct time
     * }
     */
    public static final long time$offset() {
        return time$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * duckdb_time_struct time
     * }
     */
    public static MemorySegment time(MemorySegment struct) {
        return struct.asSlice(time$OFFSET, time$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * duckdb_time_struct time
     * }
     */
    public static void time(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, time$OFFSET, time$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

