// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef bool (*duckdb_cast_function_t)(duckdb_function_info, idx_t, duckdb_vector, duckdb_vector)
 * }
 */
public final class duckdb_cast_function_t {

    private duckdb_cast_function_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        boolean apply(MemorySegment info, long count, MemorySegment input, MemorySegment output);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        duckdb_h.C_BOOL,
        duckdb_h.C_POINTER,
        duckdb_h.C_LONG,
        duckdb_h.C_POINTER,
        duckdb_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = duckdb_h.upcallHandle(duckdb_cast_function_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(duckdb_cast_function_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static boolean invoke(MemorySegment funcPtr, MemorySegment info, long count, MemorySegment input, MemorySegment output) {
        try {
            return (boolean) DOWN$MH.invokeExact(funcPtr, info, count, input, output);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

