// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int32_t year;
 *     int8_t month;
 *     int8_t day;
 * }
 * }
 */
public class duckdb_date_struct {

    duckdb_date_struct() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_h.C_INT.withName("year"),
        duckdb_h.C_CHAR.withName("month"),
        duckdb_h.C_CHAR.withName("day"),
        MemoryLayout.paddingLayout(2)
    ).withName("$anon$322:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt year$LAYOUT = (OfInt)$LAYOUT.select(groupElement("year"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t year
     * }
     */
    public static final OfInt year$layout() {
        return year$LAYOUT;
    }

    private static final long year$OFFSET = $LAYOUT.byteOffset(groupElement("year"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t year
     * }
     */
    public static final long year$offset() {
        return year$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t year
     * }
     */
    public static int year(MemorySegment struct) {
        return struct.get(year$LAYOUT, year$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t year
     * }
     */
    public static void year(MemorySegment struct, int fieldValue) {
        struct.set(year$LAYOUT, year$OFFSET, fieldValue);
    }

    private static final OfByte month$LAYOUT = (OfByte)$LAYOUT.select(groupElement("month"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t month
     * }
     */
    public static final OfByte month$layout() {
        return month$LAYOUT;
    }

    private static final long month$OFFSET = $LAYOUT.byteOffset(groupElement("month"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t month
     * }
     */
    public static final long month$offset() {
        return month$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t month
     * }
     */
    public static byte month(MemorySegment struct) {
        return struct.get(month$LAYOUT, month$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t month
     * }
     */
    public static void month(MemorySegment struct, byte fieldValue) {
        struct.set(month$LAYOUT, month$OFFSET, fieldValue);
    }

    private static final OfByte day$LAYOUT = (OfByte)$LAYOUT.select(groupElement("day"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t day
     * }
     */
    public static final OfByte day$layout() {
        return day$LAYOUT;
    }

    private static final long day$OFFSET = $LAYOUT.byteOffset(groupElement("day"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t day
     * }
     */
    public static final long day$offset() {
        return day$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t day
     * }
     */
    public static byte day(MemorySegment struct) {
        return struct.get(day$LAYOUT, day$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t day
     * }
     */
    public static void day(MemorySegment struct, byte fieldValue) {
        struct.set(day$LAYOUT, day$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

