// Generated by jextract

package org.duckdb.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int64_t millis;
 * }
 * }
 */
public class duckdb_timestamp_ms {

    duckdb_timestamp_ms() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        duckdb_h.C_LONG.withName("millis")
    ).withName("$anon$374:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong millis$LAYOUT = (OfLong)$LAYOUT.select(groupElement("millis"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t millis
     * }
     */
    public static final OfLong millis$layout() {
        return millis$LAYOUT;
    }

    private static final long millis$OFFSET = $LAYOUT.byteOffset(groupElement("millis"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t millis
     * }
     */
    public static final long millis$offset() {
        return millis$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t millis
     * }
     */
    public static long millis(MemorySegment struct) {
        return struct.get(millis$LAYOUT, millis$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t millis
     * }
     */
    public static void millis(MemorySegment struct, long fieldValue) {
        struct.set(millis$LAYOUT, millis$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

